Pre initial data s1 canzhao
flag-camp-2020-t3/Spare4Fun-Server pull request #112
Opened 2020-12-27 06:41 UTC by VLiamZhao

What I did:
1. I divided the data source into two parts: "dev" and "test".
2. I add the data in SQL file by using the CustomizeDataSourceInitializer class.
3. I tested the unit tests which were modified in CategoryDao and all tests passed.

2020-12-28 21:10 UTC, Alicewillbe requested changes
We need another discussion on this feature.

2020-12-28 21:10 UTC, Alicewillbe commented on src/main/resources/application.properties
> +spring.profiles.active=test
I believe there is no need to have variables ```spring.datasource.test.*``` because we will never have both profiles ```test``` & ```dev``` active at the same time. 
In other words, ```spring.datasource.*``` is good enough.
And here you have default profile ```test``` which is kind of OK for me.

2020-12-28 23:01 UTC, Alicewillbe commented
Resolve #97

2020-12-29 01:38 UTC, VLiamZhao commented on src/main/resources/application.properties
> +spring.profiles.active=test
Got it! I agree with you. I will modify it ASAP.

2020-12-29 02:17 UTC, closed without merging