Pre exception handling canzhao
flag-camp-2020-t3/Spare4Fun-Server pull request #114
Opened 2020-12-27 23:43 UTC by VLiamZhao

Some examples of ExceptionHandler are implemented. 
We can add the corresponding exceptions in controllers, and they will be intercepted by our handlers.

2020-12-28 21:03 UTC, Alicewillbe commented
For next time, please keep merging with updated ```main``` so that this pull request can focus merely on what you've changed for this feature.

2020-12-29 20:33 UTC, Alicewillbe requested changes

2020-12-29 20:33 UTC, Alicewillbe commented on src/main/java/com/spare4fun/core/exception/GlobalExceptionAdvice.java
> +
For exceptions methods below, I think you can take advantage of ```e.getMessage()``` and combine these to a single method.

2020-12-29 23:58 UTC, VLiamZhao commented on src/main/java/com/spare4fun/core/exception/GlobalExceptionAdvice.java
> +
Sure，I can add logger to handle it. I will modify it and request it again.

2020-12-30 22:00 UTC, closed without merging